modLoader="javafml" #mandatory
loaderVersion="[27,)" #mandatory (24 is current forge version)
[[mods]] #mandatory


modId="moundmod" #mandatory


version="0.1.0" #mandatory


displayName="Mound Mod" #mandatory


logoFile="examplemod.png" #optional


credits="Thanks for this example mod goes to Java. And HarryTalks for his tutorials." #optional
authors="Elvenar & HighAwesomeness" #optional

description='''
Mod created to add Goblins and Goblinlike items/creatures into Minecraft.
'''

[[dependencies.moundmod]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[27,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
# Here's another dependency
[[dependencies.moundmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.3]"
    ordering="NONE"
    side="BOTH"